version: '3.8'
services:
  db:
    image: 'postgres:16.2'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    ports:
      - "5432:5432"

  backend:
    build: ./api
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"