version: '3.8'
services:
  db:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    network_mode: "host"

  backend:
    build: ./api
    network_mode: "host"

  frontend:
    build: ./frontend
    network_mode: "host"